# -*- coding: utf-8 -*-
"""urdu_orpheus_colab_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bq7G6PbbA4rPkk7bDR3ylfROaiV718T2

# Urdu Orpheus: one epoch on ASLP Stage 1
This notebook uses `data_aslb/stage1_train.csv` (6,633 clips) and `stage1_validation.csv` (806 clips). It keeps `stage1_test.csv` untouched. Audio is encoded with SNAC, then the English pretrained Orpheus 3B model is adapted with Unsloth LoRA. Select **Runtime → Change runtime type → GPU**. The default 4-bit setting is intended for a T4; L4/A100 can try 16-bit.

References: [Unsloth TTS guide](https://unsloth.ai/docs/basics/text-to-speech-tts-fine-tuning), [Unsloth Orpheus Colab](https://github.com/unslothai/notebooks/blob/main/nb/Orpheus_(3B)-TTS.ipynb), [Orpheus training code](https://github.com/canopyai/Orpheus-TTS/tree/main/finetune). The training cell is adapted for a local Urdu dataset, a full epoch, and Drive checkpoints.

## 1. Mount Drive and set paths
Upload `Urdu_Orpheus_Stage1_10h_handoff.zip` to **MyDrive/orpheus_urdu/**. The supplied archive contains `processed_aslp_urdu_10h/` with the manifests and `audio/`. You may instead upload the extracted `data_aslb` folder and set `ARCHIVE_PATH = None`. Keep the CSV and audio folder together.
"""

from google.colab import drive
drive.mount('/content/drive')
from pathlib import Path
DRIVE_ROOT = Path('/content/drive/MyDrive/orpheus_urdu')
ARCHIVE_PATH = DRIVE_ROOT / 'data_aslb.zip'  # or None for extracted folder
DATA_DIR = Path('/content/processed_aslp_urdu_10h') if ARCHIVE_PATH else DRIVE_ROOT / 'data_aslb'
CACHE_DIR = DRIVE_ROOT / 'token_cache_unsloth_pretrained_v1'
OUTPUT_DIR = DRIVE_ROOT / 'checkpoints_unsloth_pretrained_v1'
MODEL_ID = 'unsloth/orpheus-3b-0.1-pretrained'
LOAD_IN_4BIT = True  # T4; try False on L4/A100 with sufficient VRAM
EPOCHS = 1
SAVE_STEPS = 250
MAX_LENGTH = 2048
CACHE_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print('GPU and memory:')
!nvidia-smi

"""## 2. Install packages and extract the data
Package installation changes only this Colab runtime. Restart the runtime if pip asks, then rerun from the first cell. The zip is extracted to fast local storage; the token cache and checkpoints stay in Drive.

"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install 'unsloth' 'snac>=1.2' 'datasets>=3.4,<4' soundfile pandas pyarrow safetensors
import zipfile
if ARCHIVE_PATH:
    assert ARCHIVE_PATH.is_file(), f'Upload the archive to {ARCHIVE_PATH}'
    if not (DATA_DIR / 'stage1_train.csv').exists():
        with zipfile.ZipFile(ARCHIVE_PATH) as z:
            bad = [n for n in z.namelist() if Path(n).is_absolute() or '..' in Path(n).parts]
            if bad: raise ValueError(f'Unsafe archive members: {bad[:3]}')
            z.extractall('/content')
assert (DATA_DIR / 'stage1_train.csv').is_file(), f'Cannot find manifest in {DATA_DIR}'
assert (DATA_DIR / 'audio').is_dir(), f'Cannot find audio directory in {DATA_DIR}'
print('Dataset:', DATA_DIR)

"""## 3. Check and clean manifests
Only NFC normalization, whitespace cleanup, and control removal are applied. The Urdu wording and punctuation stay intact. The existing speaker IDs are unreliable as voice identities, so prompts contain text alone. Review the printed examples and listen to `samples_to_review.csv` before claiming quality.

"""

import pandas as pd, unicodedata, wave, re
from IPython.display import Audio, display
def clean_text(s):
    s = unicodedata.normalize('NFC', str(s))
    s = ''.join(c for c in s if unicodedata.category(c) != 'Cc' or c in '\t\n')
    return ' '.join(s.split())
def checked_split(name):
    df = pd.read_csv(DATA_DIR / f'stage1_{name}.csv', dtype=str, keep_default_na=False)
    assert {'audio','text'} <= set(df.columns)
    df = df[['audio','text']].copy()
    df['text'] = df['text'].map(clean_text)
    bad, durations = [], []
    for i, row in df.iterrows():
        p = Path(row.audio)
        if p.is_absolute() or '..' in p.parts or not row.text or not re.search('[\u0600-\u06ff]', row.text):
            bad.append((i, 'path/text')); durations.append(0); continue
        path = DATA_DIR / p
        try:
            with wave.open(str(path), 'rb') as w:
                duration = w.getnframes()/w.getframerate()
                if w.getframerate()!=24000 or w.getnchannels()!=1 or w.getsampwidth()!=2 or not 1.9<=duration<=10.1:
                    bad.append((i, 'audio format/duration'))
            durations.append(duration)
        except Exception as e:
            bad.append((i, str(e))); durations.append(0)
    if bad: raise ValueError(f'{name}: {len(bad)} invalid rows, first: {bad[:5]}')
    if df.audio.duplicated().any(): raise ValueError(f'{name}: duplicate audio paths')
    df['duration'] = durations
    print(name, len(df), f'{sum(durations)/3600:.3f} hours')
    return df
train_df = checked_split('train')
val_df = checked_split('validation')
assert not set(train_df.audio) & set(val_df.audio), 'Overlapping train/validation clips'
display(train_df.head(3))
sample = train_df.iloc[0]
display(Audio(str(DATA_DIR / sample.audio)))
print('Transcript:', sample.text)

"""## 4. Encode speech with SNAC; cache in Drive
Each split is saved in 100-row Parquet chunks, so rerunning after a disconnect resumes completed chunks. Do not change the manifests or model/token format while reusing a cache directory; choose a new `CACHE_DIR` if you do. A failed chunk is retried, and invalid rows cause an error rather than being silently dropped.

"""

from unsloth import FastLanguageModel, is_bfloat16_supported  # import before transformers
import torch, numpy as np, soundfile as sf, gc
from snac import SNAC
from transformers import AutoTokenizer, AutoConfig
from tqdm.auto import tqdm
assert torch.cuda.is_available(), 'Enable a Colab GPU runtime.'
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model_vocab_size = AutoConfig.from_pretrained(MODEL_ID).vocab_size
snac = SNAC.from_pretrained('hubertsiuzdak/snac_24khz').eval().cuda()
SPECIAL = dict(end_text=128009, start_speech=128257, end_speech=128258, start_human=128259, end_human=128260, start_ai=128261, end_ai=128262)
AUDIO_BASE = 128266
def encode_row(row):
    audio, sr = sf.read(DATA_DIR / row.audio, dtype='float32')
    assert sr == 24000 and audio.ndim == 1 and np.isfinite(audio).all()
    signal = torch.from_numpy(audio).to('cuda').view(1,1,-1)
    with torch.inference_mode(): codes = snac.encode(signal)
    c0, c1, c2 = [c[0].cpu().tolist() for c in codes]
    assert len(c1)>=2*len(c0) and len(c2)>=4*len(c0)
    frames = []
    for i in range(len(c0)):
        frame = [c0[i], c1[2*i]+4096, c2[4*i]+8192, c2[4*i+1]+12288, c1[2*i+1]+16384, c2[4*i+2]+20480, c2[4*i+3]+24576]
        if not frames or frame[0] != frames[-1][0]: frames.append(frame)
    audio_ids = [AUDIO_BASE + code for frame in frames for code in frame]
    text_ids = tokenizer.encode(row.text, add_special_tokens=True)
    ids = [SPECIAL['start_human']] + text_ids + [SPECIAL['end_text'], SPECIAL['end_human'], SPECIAL['start_ai'], SPECIAL['start_speech']] + audio_ids + [SPECIAL['end_speech'], SPECIAL['end_ai']]
    assert len(ids) <= MAX_LENGTH, f'Sequence too long ({len(ids)}); adjust MAX_LENGTH or exclude clip after review'
    assert max(ids) < model_vocab_size, f'Audio token exceeds model vocabulary: {max(ids)} >= {model_vocab_size}'
    return {'input_ids': ids, 'attention_mask': [1]*len(ids), 'labels': ids.copy()}
def encode_split(df, name, chunk_size=100):
    folder = CACHE_DIR / name
    folder.mkdir(parents=True, exist_ok=True)
    for start in tqdm(range(0, len(df), chunk_size), desc=name):
        dest = folder / f'{start:06d}.parquet'
        if dest.exists():
            if len(pd.read_parquet(dest)) == min(chunk_size, len(df)-start): continue
            raise ValueError(f'Incomplete cache chunk: {dest}; inspect it before retrying')
        rows = [encode_row(row) for row in df.iloc[start:start+chunk_size].itertuples()]
        temp = folder / f'{start:06d}.tmp.parquet'
        pd.DataFrame(rows).to_parquet(temp, index=False)
        temp.replace(dest)
        del rows
    return sorted(str(p) for p in folder.glob('*.parquet'))
train_files = encode_split(train_df, 'train')
val_files = encode_split(val_df, 'validation')
del snac
gc.collect(); torch.cuda.empty_cache()
print('Cached chunks:', len(train_files), len(val_files))

"""## 5. Train for one epoch with Drive checkpoints
Unsloth runs LoRA over the English pretrained Orpheus model. The prepared Parquet files contain real audio tokens; text-only tokenization cannot teach speech. Dynamic padding keeps memory use down. Rerunning resumes the latest Drive checkpoint. The final `adapter_final` needs the same base `MODEL_ID` for inference.

"""

from unsloth import FastLanguageModel, is_bfloat16_supported
from datasets import load_dataset
from transformers import Trainer, TrainingArguments
from transformers.trainer_utils import get_last_checkpoint
ds = load_dataset('parquet', data_files={'train': train_files, 'validation': val_files})
assert len(ds['train']) == len(train_df) and len(ds['validation']) == len(val_df)
print(ds)
PAD = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
def collate(examples):
    width = max(len(x['input_ids']) for x in examples)
    return {
        'input_ids': torch.tensor([list(x['input_ids']) + [PAD]*(width-len(x['input_ids'])) for x in examples], dtype=torch.long),
        'attention_mask': torch.tensor([list(x['attention_mask']) + [0]*(width-len(x['attention_mask'])) for x in examples], dtype=torch.long),
        'labels': torch.tensor([list(x['labels']) + [-100]*(width-len(x['labels'])) for x in examples], dtype=torch.long),
    }
model, train_tokenizer = FastLanguageModel.from_pretrained(model_name=MODEL_ID, max_seq_length=MAX_LENGTH, dtype=None, load_in_4bit=LOAD_IN_4BIT)
assert len(train_tokenizer) == len(tokenizer), 'Training tokenizer differs from preprocessing tokenizer'
model = FastLanguageModel.get_peft_model(model, r=16, target_modules=['q_proj','k_proj','v_proj','o_proj','gate_proj','up_proj','down_proj'], lora_alpha=32, lora_dropout=0, bias='none', use_gradient_checkpointing='unsloth', random_state=3407)
model.print_trainable_parameters()
args = TrainingArguments(output_dir=str(OUTPUT_DIR), num_train_epochs=EPOCHS, per_device_train_batch_size=1, gradient_accumulation_steps=8, learning_rate=2e-4, lr_scheduler_type='cosine', warmup_ratio=0.03, fp16=not is_bfloat16_supported(), bf16=is_bfloat16_supported(), logging_steps=25, save_strategy='steps', save_steps=SAVE_STEPS, save_total_limit=3, eval_strategy='no', report_to='none', optim='adamw_8bit', remove_unused_columns=False, seed=3407)
trainer = Trainer(model=model, args=args, train_dataset=ds['train'], data_collator=collate)
last = get_last_checkpoint(str(OUTPUT_DIR))
print('Resuming from:', last or 'start')
result = trainer.train(resume_from_checkpoint=last)
trainer.save_model(str(OUTPUT_DIR / 'adapter_final'))
train_tokenizer.save_pretrained(str(OUTPUT_DIR / 'adapter_final'))
trainer.save_metrics('train', result.metrics)
print('Saved adapter:', OUTPUT_DIR / 'adapter_final')

"""## 6. Validation loss and next steps
Run this after training to get a held-out loss. It measures token prediction, not speech naturalness; listen to generated Urdu speech before judging quality. The test split remains untouched.

"""

# Transformers' notebook progress callback can fail on standalone evaluation after trainer.train().
from transformers.utils.notebook import NotebookProgressCallback
trainer.remove_callback(NotebookProgressCallback)
metrics = trainer.evaluate(eval_dataset=ds['validation'])
trainer.save_metrics('validation', metrics)
print(metrics)

URDU_TEXT = 'آج موسم بہت خوشگوار ہے اور ہم سب باہر سیر کے لیے جا رہے ہیں۔'
MAX_NEW_TOKENS = 900  # increase for longer sentences; 7 tokens make one SNAC frame
from IPython.display import Audio, display
from snac import SNAC
import soundfile as sf
if 'model' not in globals():
    from unsloth import FastLanguageModel
    from peft import PeftModel
    base_model, tokenizer = FastLanguageModel.from_pretrained(model_name=MODEL_ID, max_seq_length=MAX_LENGTH, dtype=None, load_in_4bit=LOAD_IN_4BIT)
    model = PeftModel.from_pretrained(base_model, str(OUTPUT_DIR / 'adapter_final'))
FastLanguageModel.for_inference(model)
model.eval()
prompt_ids = [128259] + tokenizer.encode(URDU_TEXT, add_special_tokens=True) + [128009, 128260, 128261, 128257]
inputs = torch.tensor([prompt_ids], dtype=torch.long, device='cuda')
with torch.inference_mode():
    output = model.generate(input_ids=inputs, max_new_tokens=MAX_NEW_TOKENS, do_sample=True, temperature=0.6, top_p=0.95, repetition_penalty=1.1, eos_token_id=128258, pad_token_id=128263, use_cache=True)
new_ids = output[0, inputs.shape[1]:].tolist()
if 128258 in new_ids: new_ids = new_ids[:new_ids.index(128258)]
frames = []
offsets = [0, 4096, 8192, 12288, 16384, 20480, 24576]
for i in range(0, len(new_ids)-6, 7):
    block = new_ids[i:i+7]
    if any(not 0 <= token - 128266 - offset < 4096 for token, offset in zip(block, offsets)):
        break
    frames.append([token - 128266 - offset for token, offset in zip(block, offsets)])
if not frames: raise RuntimeError(f'No complete SNAC frames generated. First output IDs: {new_ids[:20]}')
codes = [
    torch.tensor([[f[0] for f in frames]], dtype=torch.long),
    torch.tensor([[v for f in frames for v in (f[1], f[4])]], dtype=torch.long),
    torch.tensor([[v for f in frames for v in (f[2], f[3], f[5], f[6])]], dtype=torch.long),
]
decoder = SNAC.from_pretrained('hubertsiuzdak/snac_24khz').eval().cpu()
with torch.inference_mode(): waveform = decoder.decode(codes).squeeze().cpu().numpy()
audio_path = OUTPUT_DIR / 'urdu_test.wav'
sf.write(audio_path, waveform, 24000)
print('Saved:', audio_path, '| seconds:', round(len(waveform)/24000, 2), '| frames:', len(frames))
display(Audio(waveform, rate=24000))

"""## 8. After training
One epoch is a first adaptation experiment, and transcript/audio mismatches can dominate quality. To continue beyond one epoch, set `EPOCHS` higher and rerun the training cell; it will resume from the last checkpoint. Keep the Drive checkpoint folder. If Colab reports out-of-memory, use a larger GPU or reduce LoRA rank; a lower `MAX_LENGTH` requires rebuilding the token cache and reviewing clips that exceed the limit.

Keep the base model ID, token cache, and adapter together.

"""